package cplir_c.advent_of_code_2020;

public class Day6 {
    private static final String INPUT = "rypdeiqkbgacnxwumhtozfjvs\n" + "mhrqdwtxcfjuseknozipayvbg\n"
            + "gunjdtebovsyihraczkmqxfpw\n" + "pqcnduafgkbzjhvirxtwmesoy\n" + "\n" + "wmghxlzctojyspn\n" + "jtohwzpvkmycs\n"
            + "cuvkjoyheztmqswp\n" + "\n" + "detmwhk\n" + "emklvdf\n" + "yemupdxq\n" + "\n" + "hdxektmfycarwpio\n"
            + "epiamhowxdcktfrvy\n" + "octximeakfhrwdzpy\n" + "\n" + "pxwnzji\n" + "jrpoawxiv\n" + "wjiqxmp\n" + "\n" + "ch\n"
            + "loct\n" + "wxmtjeup\n" + "hfyxktz\n" + "birvsdq\n" + "\n" + "rluz\n" + "zlwruq\n" + "zlur\n" + "lrzu\n" + "\n"
            + "omcwsj\n" + "sqkjwruc\n" + "cwpklf\n" + "vtyadxcnwzg\n" + "\n" + "clfnzvjhpiybwoksxm\n" + "snzxvyfopbmhijl\n"
            + "nxymlhjvfzspbio\n" + "\n" + "jwevzxdhpyrifcuksqgt\n" + "fglozbuswkmdr\n" + "\n" + "jvhgezpqurxalk\n"
            + "qhizygwbtfupljcsmo\n" + "\n" + "jge\n" + "r\n" + "l\n" + "rg\n" + "\n" + "icgh\n" + "gihc\n" + "ghpvdkic\n"
            + "gwhcfi\n" + "\n" + "woerv\n" + "ow\n" + "powf\n" + "\n" + "zhqvdxburfmstkloiypgwj\n"
            + "bpzcnvwudtkhfomsrqayiegjl\n" + "\n" + "bjhagpqxvnrlsufytz\n" + "yjdnqhosbtuzexgpvar\n" + "qbksyczativhgprnxmj\n"
            + "\n" + "vdmretq\n" + "tmrevdq\n" + "rdqemgv\n" + "jnmqvedrzu\n" + "dmgrqve\n" + "\n" + "namzrqsdlftvyexkopu\n"
            + "fvtneaqyurozkpmxsdl\n" + "xpznavflsetruykomdq\n" + "sbxdlymekrqanvztfupo\n" + "\n" + "whjs\n" + "hsjw\n"
            + "shwj\n" + "\n" + "szpqmkodtfgeivxybchnjlr\n" + "yzrpefkjichgmvbodxtns\n" + "inxafhbszovdtmjgycrepk\n" + "\n"
            + "lnixphrqcuszfbtwyeod\n" + "doupcibeqshyrfzlx\n" + "oprqsdhixfuzyclbe\n" + "\n" + "ojnv\n" + "jnv\n" + "vjn\n"
            + "ajnv\n" + "\n" + "ymtfzirplknbejwucdaqg\n" + "eczmygatkuvwiprqjldnfb\n" + "ydqbeflnikwjprmzutagc\n" + "\n"
            + "gvbithwxzdyfkoep\n" + "ixyozwhevbgdftk\n" + "fhpozxydktgbewivc\n" + "wodpgnvektbqhxyfiz\n"
            + "krxfwoystdgbizevh\n" + "\n" + "qnp\n" + "npfq\n" + "\n" + "wylxqpgvuafbtjneid\n" + "lfjamczetspkwvbdqoih\n"
            + "\n" + "hpbjdyiwsg\n" + "dipwjhybg\n" + "pcubgwmridjyh\n" + "dgpyjihwb\n" + "\n" + "gcbxv\n" + "vcbg\n" + "\n"
            + "pjgsyzteohwaibnc\n" + "ohlwfgdvtczsnpejyxaqi\n" + "pzmewhojayscbgint\n" + "\n" + "foytjxbhiwc\n"
            + "nxfigpqyhuckm\n" + "\n" + "ta\n" + "at\n" + "ato\n" + "tao\n" + "etaf\n" + "\n" + "tyebulroispdqm\n" + "cheqfk\n"
            + "cxnqejfwag\n" + "qaze\n" + "\n" + "xs\n" + "mexs\n" + "vfxls\n" + "sehx\n" + "\n" + "plvqenkgiwj\n"
            + "eihjplvnwkgq\n" + "\n" + "bcteiamnzljyrvhqxwpuo\n" + "ctleshvprmknxibjyozgqwau\n" + "venmchpqjxzwoultriyba\n"
            + "malqychnozbxwtjepirvu\n" + "\n" + "qlvcexgauwkonr\n" + "ysrvfxtigcnqmdjab\n" + "nvlpxgzacohrq\n" + "\n" + "r\n"
            + "r\n" + "r\n" + "r\n" + "r\n" + "\n" + "sth\n" + "tsh\n" + "ths\n" + "hts\n" + "hst\n" + "\n" + "j\n" + "j\n"
            + "c\n" + "j\n" + "\n" + "fptakxrwqzghcid\n" + "hwudjvteyqnmsxbzrl\n" + "\n" + "fj\n" + "fj\n" + "fj\n" + "\n"
            + "qd\n" + "e\n" + "\n" + "dfqagyzoluemikxhr\n" + "hmfzegoyikalrbu\n" + "\n" + "amz\n" + "zcwma\n" + "zma\n"
            + "zma\n" + "zam\n" + "\n" + "iavezojwpxgf\n" + "azxqivwsgufjo\n" + "vfwaoguizjx\n" + "\n" + "vdytwaugpmn\n"
            + "ywgtvdaunp\n" + "rdujgtknywpav\n" + "\n" + "hcjobxdagvtzureimn\n" + "egouxjizsrpmatncbv\n"
            + "bovgcisajmzedturxn\n" + "ymcauqenrwobtjvxzgk\n" + "\n" + "z\n" + "k\n" + "mt\n" + "b\n" + "\n" + "onxdjc\n"
            + "kij\n" + "jekrlws\n" + "pqmtyjvbz\n" + "\n" + "lrekpb\n" + "cs\n" + "f\n" + "\n" + "miukhetbgpcofnywld\n"
            + "fgypmoutcnewkdlhib\n" + "nmegdpfcbtkhuoyliw\n" + "iewbnmufpltydcokhg\n" + "\n" + "fm\n" + "zc\n" + "\n" + "q\n"
            + "g\n" + "q\n" + "q\n" + "\n" + "d\n" + "qov\n" + "u\n" + "\n" + "vpekhuanwyitdbzq\n" + "taivnxwfphzkbueyld\n"
            + "\n" + "ivuq\n" + "iuqv\n" + "viqu\n" + "iquv\n" + "uviq\n" + "\n" + "w\n" + "x\n" + "g\n" + "\n" + "aqvz\n"
            + "msitp\n" + "\n" + "epigzysdnhvjwfl\n" + "eiwvzspyfnjdghl\n" + "ewizvgjnspfdylh\n" + "ifpjzlwedysgvhn\n"
            + "shzlefdvpgiynjw\n" + "\n" + "gfcpvheli\n" + "leuizvgcfhpyw\n" + "jrolbshdivfg\n" + "\n" + "nozm\n" + "rzbe\n"
            + "rzeb\n" + "\n" + "i\n" + "i\n" + "i\n" + "i\n" + "\n" + "l\n" + "i\n" + "w\n" + "xl\n" + "cvd\n" + "\n"
            + "prezgubljmyq\n" + "hdjgxymcrbqutzk\n" + "ugsvrjqybzm\n" + "rqbmwuzygj\n" + "ioqzjaufbgrmy\n" + "\n"
            + "lvkwrpiafgehuj\n" + "bighyasoqfk\n" + "\n" + "zjopywe\n" + "yceowzjp\n" + "qpijoyzew\n"
            + "hbfgusynojvrezxwpadlk\n" + "etzywpoj\n" + "\n" + "lyawqpmirognzstbduc\n" + "luieajxqpzokvygftrbns\n" + "\n"
            + "xpbjvgmclwyaeui\n" + "bmlxpsueqgciyjv\n" + "tvcnmrlgybjeuipx\n" + "vyeaxbjufomicpltg\n" + "\n" + "scbpelzjd\n"
            + "qicbopdefs\n" + "bescdp\n" + "spbcejgd\n" + "\n" + "izqc\n" + "zc\n" + "vcz\n" + "zc\n" + "\n"
            + "zxtpqjousimgwd\n" + "ldjvupmykawohsxqf\n" + "oupwbjqdexsm\n" + "\n" + "nldjubr\n" + "jlrudbn\n" + "ldnujrb\n"
            + "unldbjr\n" + "\n" + "gvrhtzabkpjwin\n" + "iylsvcqftb\n" + "\n" + "ieurvztojxs\n" + "utwrozyhsjpv\n"
            + "djtouzvr\n" + "ufznbqkatjvcol\n" + "\n" + "lauocyjix\n" + "oacxleiju\n" + "jalucorshi\n" + "\n" + "y\n" + "xyj\n"
            + "yp\n" + "y\n" + "\n" + "tzdopeirawxqj\n" + "xfjitporuzwhmka\n" + "owkfpxhtiazrj\n" + "\n" + "xabdw\n"
            + "xcbadw\n" + "dprybzwjxa\n" + "bcxawdv\n" + "\n" + "qhmetwcuiagpv\n" + "pvcmhigewqau\n" + "wvqheiacumgp\n"
            + "unmpjlciwehbgzqav\n" + "haevgiqumcpw\n" + "\n" + "fndv\n" + "dik\n" + "nmcjhfbs\n" + "lxzquaproeyw\n"
            + "msjfgti\n" + "\n" + "rxcq\n" + "cslmqje\n" + "\n" + "vkl\n" + "v\n" + "umr\n" + "\n" + "tgflck\n" + "tbmafhgjx\n"
            + "ctgwf\n" + "gwtf\n" + "\n" + "afn\n" + "anf\n" + "fna\n" + "fgan\n" + "\n" + "kbypmroflcgsijqt\n" + "merbsy\n"
            + "yuazxsnwrvmb\n" + "\n" + "mbqeotcwa\n" + "wacbtzme\n" + "\n" + "ykgwomscpdr\n" + "udsmiqophxgazc\n" + "\n"
            + "byhgswqf\n" + "ziruakpdxenojt\n" + "mlhyqcbfgv\n" + "\n" + "sjcpmgfnqkbtvh\n" + "tjhaocknsqgvzmfxb\n"
            + "hvskbjtmfncqg\n" + "svgmbtkjfchqwn\n" + "\n" + "vxnyazclrhigju\n" + "tzejprxgiuvnhl\n" + "\n"
            + "kfgrnpwahvuzbtdeosxycjl\n" + "codeskpxziflhqmtnw\n" + "nzpkocwlfexhdts\n" + "\n" + "amxeu\n" + "xuem\n"
            + "muxe\n" + "xmue\n" + "\n" + "nfdekjvaswxhlizumqcr\n" + "ahvenfjwmqukxrzslcdi\n" + "amzhrqdvknuwfelcjixs\n"
            + "ahzxsfnqcirwdvlejmku\n" + "kmivhzfsdxrwueqcajln\n" + "\n" + "ahutglpcfobw\n" + "inbgfhawctlu\n"
            + "glxabyjwdersfhut\n" + "glwnbvhtfqua\n" + "\n" + "tkvnhiguafzpbryomqs\n" + "fjuqmyizhtdvrapbgok\n" + "\n"
            + "lavnu\n" + "anuv\n" + "nuva\n" + "vnua\n" + "avnu\n" + "\n" + "dsypquzvk\n" + "yfvpuwkqxzd\n" + "zaqdpkvuhoy\n"
            + "\n" + "hztcgilumwfjqvdx\n" + "ljdzmfxhwnocukva\n" + "wdzxlcphvfmruj\n" + "vwtgemuhljsyfrqdxzbpc\n" + "\n"
            + "gylhmqsfo\n" + "flhgsmqoy\n" + "yflgmhosq\n" + "yhsomlfqg\n" + "\n" + "njrtykmqhpsbl\n" + "ehrqnbmtpkyloz\n"
            + "tqnydrhcxmbkp\n" + "eykmrhnqlpbt\n" + "\n" + "x\n" + "t\n" + "t\n" + "\n" + "xmbzthspyqiwkre\n" + "kmertowqzhy\n"
            + "wntlghzqvuaym\n" + "\n" + "anzmrgh\n" + "hvbz\n" + "ikcqewfo\n" + "\n" + "bmhkpvatlxsqe\n" + "qhlsvmwkaxtbep\n"
            + "afvyqxopmebkths\n" + "kmaqhpbvxsect\n" + "smhbqatxvekp\n" + "\n" + "rhlvqfi\n" + "fhqlvir\n" + "vlfqihr\n"
            + "frvhqil\n" + "hrfwaiyqvl\n" + "\n" + "kqp\n" + "bkpq\n" + "qknpb\n" + "kfbnqp\n" + "tmqlpk\n" + "\n"
            + "zamldqftosjchig\n" + "sgoltqfzhcmida\n" + "ilchsoqyzdafmteg\n" + "omtzqschailgdf\n" + "\n" + "dqtzj\n"
            + "qdzjt\n" + "wjqbztd\n" + "tqdzj\n" + "\n" + "f\n" + "f\n" + "\n" + "a\n" + "a\n" + "e\n" + "a\n" + "\n"
            + "lthopwunzesadc\n" + "agcpuiqwbezrfm\n" + "\n" + "vecitwkr\n" + "evrwktc\n" + "twejkvcly\n" + "tvweckr\n" + "\n"
            + "ivhprtaqxluznd\n" + "czhpmktnbarjuqx\n" + "hntzuxaqfwpr\n" + "ztqfxhunpdagrsw\n" + "\n" + "yearmjzfvoglksutx\n"
            + "ytxonejacwgkspvbl\n" + "\n" + "gctxse\n" + "cjgetx\n" + "xocetga\n" + "\n" + "uedfocpwivngk\n" + "prxuiveon\n"
            + "hpovnuimel\n" + "pexivunoj\n" + "\n" + "cdsqhptunrmgjvfiozl\n" + "srvuhlgimntpjfdoqcz\n"
            + "hotpzrcfvsgdinqljum\n" + "mtdfnzogrluvhsqjpic\n" + "imshvtfzoprnqcjlgdu\n" + "\n" + "qvitpoadjkfe\n"
            + "fhtwujgxmyvqp\n" + "fvqtjp\n" + "\n" + "igcu\n" + "cpzkirmaqeuvyjblt\n" + "uwfhcio\n" + "ufci\n" + "\n"
            + "olpayrzujbxigkmtdwfvs\n" + "mnlajiogzfyvxdptbkr\n" + "gxkjabvmdptlfyiozr\n" + "\n" + "ozuitjkyrplmwhx\n"
            + "wqilxmrjzphk\n" + "zmpflxwkrjhi\n" + "\n" + "xklnmyjz\n" + "tbywrnecm\n" + "qasm\n" + "\n" + "nmqezcib\n"
            + "bqcine\n" + "bqeiwnc\n" + "\n" + "gfwcuktlovqaxinrmsye\n" + "apuxbreclsovh\n" + "lrozacsuevxy\n" + "\n"
            + "sbirnjalhp\n" + "sjlhabinpr\n" + "spiyalnhjrb\n" + "nlahrzjibspf\n" + "phsinblragj\n" + "\n"
            + "qshiwtzunymecpkojgf\n" + "ycintzem\n" + "mtxbzyneicl\n" + "ntmzacvdyie\n" + "inledacymzt\n" + "\n" + "zikd\n"
            + "wfrtoc\n" + "xd\n" + "\n" + "b\n" + "q\n" + "\n" + "jtgrvpc\n" + "vnpob\n" + "\n" + "mxa\n" + "bgpat\n" + "av\n"
            + "\n" + "kluxigjtrnsqmbfypw\n" + "gilnxrjwumoykbsfpth\n" + "\n" + "mxufknlzeria\n" + "xraflenbiupmk\n"
            + "dxlijrknueacmyf\n" + "\n" + "rcnby\n" + "uhmilk\n" + "\n" + "feojnrqsdpwclkaiyt\n" + "kowqnhfclimjztpybd\n"
            + "xvcptleiwdofqkjnsy\n" + "\n" + "ugkailsnrj\n" + "banglk\n" + "unsglka\n" + "nlvagkc\n" + "\n" + "dwgqjpsby\n"
            + "huskprjxgvow\n" + "\n" + "psd\n" + "aspdm\n" + "dps\n" + "dsp\n" + "psd\n" + "\n" + "thnzwocdrfyeagim\n"
            + "zmfuiecortkbgdyw\n" + "\n" + "twjeozqfdvsbcyiarmkguh\n" + "oqtrmfsavdzwbejihyucgk\n" + "\n" + "turasdgcevhmxkp\n"
            + "kxmcagstlh\n" + "cbhmxkgats\n" + "\n" + "sxiezthakwvqb\n" + "sewmhkiqzfxatvgbu\n" + "vqathkezswxib\n"
            + "xwthkbvziseqa\n" + "\n" + "ewxibk\n" + "tpf\n" + "rz\n" + "\n" + "nwztryqmofi\n" + "rjyqwhmfzostc\n"
            + "tlvaurxdpkbzfgmyeo\n" + "\n" + "imzerbtfdn\n" + "teifxzny\n" + "enytifz\n" + "\n" + "rcvuafzdqkxweg\n"
            + "cgvaqxewzdyrfuk\n" + "\n" + "kbmjndsal\n" + "adjlbisnm\n" + "mdbsklnaj\n" + "nbasdljm\n" + "\n" + "qvolp\n"
            + "qckuzi\n" + "qritmn\n" + "\n" + "lqcejxk\n" + "wtxeqkcl\n" + "jlxqekc\n" + "\n" + "vqregkolsbfdx\n"
            + "qkvsoeuxrbf\n" + "jkaixwvrqbfose\n" + "\n" + "ctogmvsxiauy\n" + "szuhoqagtwcflikyd\n" + "ctoyuagsnvi\n"
            + "utygcranvosi\n" + "citoygeusa\n" + "\n" + "fuwk\n" + "yewkljpxi\n" + "\n" + "zarpyjehu\n" + "putzh\n"
            + "ptnkze\n" + "zplgbvm\n" + "zhstyqip\n" + "\n" + "hrxfvwopsaymtgc\n" + "xfaywpovkgtcsmzunrjh\n"
            + "vxgmrhcowsytafpi\n" + "\n" + "cipegfjmxbdzutorshn\n" + "efvnwuaoipbyrjtgd\n" + "\n" + "wjtryvx\n" + "rtxjbyw\n"
            + "nkrpxjolqeu\n" + "\n" + "wqjmgluhebv\n" + "jsgqirvulf\n" + "\n" + "hljupxyodbzrg\n" + "lakmhpqogvucnxf\n" + "\n"
            + "yjuwmvanoxs\n" + "swvadnujxm\n" + "iwvzrutpsfgjxqnm\n" + "\n" + "pzdhvwcjekifnmb\n" + "vnkmzhboiqdjp\n" + "\n"
            + "hqrpeaktlvsjmdcwufnyzbo\n" + "qdvruncsmtyhoepwixkzgjf\n" + "gqsdzvpmhrjntifcuywkoe\n" + "\n" + "xwszdpuln\n"
            + "otbha\n" + "tjo\n" + "\n" + "waqvmjecpsyhfztlbgodn\n" + "gmaewohbzjnytvcfqp\n" + "ofyaizgvhnbtjqmep\n"
            + "odjygheabpfztnqmvk\n" + "\n" + "ezb\n" + "buze\n" + "zbe\n" + "ebz\n" + "zeb\n" + "\n" + "z\n" + "z\n" + "z\n"
            + "\n" + "vfcjbpaiut\n" + "fjagupcio\n" + "\n" + "my\n" + "ym\n" + "my\n" + "ym\n" + "\n" + "lhqavgbsef\n"
            + "fvhqbegsla\n" + "\n" + "p\n" + "pfojb\n" + "\n" + "gyavhelf\n" + "plefo\n" + "\n" + "mirkdqulwbsctjvgxop\n"
            + "bwptsyqrckfjgxliovm\n" + "xdswvpuckjlqgibotrm\n" + "qcwixtbvkplsjrgom\n" + "\n" + "lrjt\n" + "ltr\n" + "trl\n"
            + "\n" + "nzuy\n" + "noy\n" + "jbynz\n" + "bn\n" + "fkctn\n" + "\n" + "uxifynkerjas\n" + "fxykznugtcj\n"
            + "bfyknzuxchj\n" + "qgkfmdjxynwu\n" + "jduxknfyh\n" + "\n" + "rgq\n" + "rg\n" + "yp\n" + "\n" + "inbvhkjzegyau\n"
            + "shxbcotnuda\n" + "\n" + "xtpyoswvjhueimdafcl\n" + "odmjlhvepatuysxfbwci\n" + "\n" + "gfx\n" + "f\n"
            + "dfeikvhjqz\n" + "f\n" + "\n" + "nryktcwsaixulom\n" + "wusiydlktonmcxra\n" + "xtikuqroycnsalwm\n" + "\n" + "mp\n"
            + "m\n" + "ztm\n" + "m\n" + "m\n" + "\n" + "lxohyprcwdgfz\n" + "ownfhacrlzxydeg\n" + "rhofgywdlxc\n"
            + "fhcldyrgboxw\n" + "qfhoygdxlcwr\n" + "\n" + "mrigdkbhzuonxvwtsejcp\n" + "xrwnmbzohcteyfdkpisuqgj\n"
            + "ngiobsrhvdzweukmtpxjc\n" + "drocwhmseuxgkinbztpj\n" + "\n" + "xpuchemftsnyakqoljwrd\n"
            + "dksrjfheqmcxuotwnglap\n" + "tmjpalxnrswhuekdyocqf\n" + "\n" + "xftzuvoksbai\n" + "ndgmechlpjti\n" + "\n"
            + "ygjwtmhqsierucdlkxfv\n" + "ufriqgwdtysjevxhmkcl\n" + "tokicjvdlmwfzxrasphqeg\n" + "iyjtgwmcelhksrdxqvf\n" + "\n"
            + "rvzhcsjgd\n" + "gdsjcvhrz\n" + "hjvdsgczr\n" + "vjhzdgcrs\n" + "rchvjsgztd\n" + "\n" + "trezphilc\n"
            + "yzfnqrbli\n" + "\n" + "qkofmyptcnwjsxlgaivbuzh\n" + "vbostfpnwuzagmjirlhqck\n" + "vasbchflkwjmngztopuiq\n"
            + "utjikgmorpnfaqwvzchdbls\n" + "ultmzaskwionhvgqpbcfj\n" + "\n" + "aivo\n" + "n\n" + "i\n" + "mqergs\n" + "pv\n"
            + "\n" + "rjgbw\n" + "wjrbg\n" + "gjwrb\n" + "\n" + "hwmxaigndkrvfzslo\n" + "hiamrnksowxdgfzlv\n"
            + "hkiornfwlmaxgzuvds\n" + "mnvwkdfigshxalorz\n" + "\n" + "pkygn\n" + "pygnzk\n" + "kuvynp\n" + "yknpg\n" + "\n"
            + "itxjom\n" + "mtoreix\n" + "omidqtgsnpc\n" + "eukmyioth\n" + "\n" + "vdwjtnrsbcm\n" + "smjtngvobycrwd\n"
            + "cjtvdanswrmb\n" + "bdrmcjtvsnw\n" + "\n" + "zoays\n" + "isyzao\n" + "flyzsoh\n" + "sziyo\n" + "\n" + "mth\n"
            + "mx\n" + "vpwyd\n" + "\n" + "gyoarlze\n" + "uziptwenxl\n" + "aroezlv\n" + "eclkz\n" + "\n"
            + "cevajtinmwfoukhsdzpyrx\n" + "sjtrelpfmgxdzwkbch\n" + "pcfjrleqxkzthsdmw\n" + "\n" + "siwrzbtkpgcy\n"
            + "fpsobikx\n" + "xsipkb\n" + "pkudsbi\n" + "ksbdnmphxi\n" + "\n" + "rt\n" + "it\n" + "ptsknv\n" + "jt\n" + "\n"
            + "zcxwh\n" + "rcifke\n" + "chz\n" + "\n" + "jbadzfryviqumgsxcel\n" + "vghfzqrxcmebyid\n" + "egyzfbmtqrhdixvc\n"
            + "\n" + "qundsy\n" + "nyquds\n" + "snyeduq\n" + "\n" + "dyxm\n" + "y\n" + "\n" + "xczlmdvehwarin\n"
            + "dmxehrcviazlw\n" + "\n" + "qhzsntxcl\n" + "hewbptlv\n" + "trwlihs\n" + "kgljmtudha\n" + "hloft\n" + "\n"
            + "zugp\n" + "plugh\n" + "\n" + "n\n" + "n\n" + "wen\n" + "n\n" + "\n" + "ajnpdutlwqrm\n" + "rkjmqgauwlndotx\n"
            + "umtajnqdlwker\n" + "\n" + "rkfgeadhcoxzwtbqnjusilymp\n" + "fbnrpwixalqzeskytgcmjoud\n"
            + "nuomgcwzbyjqipfkrdaxtlse\n" + "ykjbeigafqodmsxwcztlnpru\n" + "\n" + "sgpxdjumiwhetbl\n" + "wagnkvylcmqrzxf\n"
            + "\n" + "qpwdnblezgkcas\n" + "pzalvqnfebcdgksw\n" + "wclkgspdbqnzae\n" + "sgebqadzwclnpk\n" + "\n"
            + "hsdvxqrbegzpuak\n" + "zvaprehkgdqbusx\n" + "\n" + "trhxk\n" + "rokh\n" + "uhkr\n" + "rkh\n" + "htmrkp\n" + "\n"
            + "ayjmlkhqefvrgiobswpzxut\n" + "kgqdnvslwhpxjmryuaezto\n" + "\n" + "xdnobmsceipwgyqtvkazlu\n"
            + "jzyougkeavxtmslficqpdrh\n" + "aieoyslqxgvhzfdtkupcjm\n" + "\n" + "oekdcqtvhfsmwylaziubgjx\n"
            + "cseyloawjthviqgudfkbz\n" + "agqkrlebidofhtwujzyvscn\n" + "\n" + "ou\n" + "oy\n" + "oa\n" + "you\n" + "\n"
            + "kjrzmptbna\n" + "iacpmjzkhulot\n" + "pmjanvkzte\n" + "\n" + "rpdqax\n" + "apdrnziqb\n" + "\n" + "mochksjz\n"
            + "chzskmjo\n" + "cmkzhjos\n" + "cjkshzom\n" + "\n" + "braqipxm\n" + "pbamxrq\n" + "maopqrxb\n" + "\n"
            + "sezkqwtljnoy\n" + "stlnowkejqzy\n" + "kyeljtnaqwdzso\n" + "sleznjotwyqk\n" + "\n" + "a\n" + "r\n" + "c\n" + "\n"
            + "ymuxdtjlsovq\n" + "kdomytxrqlhsjun\n" + "xoylgbdstzjqmu\n" + "spxqoytmujld\n" + "lxtsmocuyqjd\n" + "\n"
            + "wktsrjxdlizaefqbo\n" + "zjbxldwsqfoaertik\n" + "lqwktdoesxfijbrza\n" + "fkbshvtexolqrimajwd\n" + "\n" + "rplog\n"
            + "jifvbd\n" + "hus\n" + "zpaymx\n" + "\n" + "dljqhy\n" + "mshry\n" + "iahwgyt\n" + "lzhjkebyq\n" + "rykph\n" + "\n"
            + "o\n" + "l\n" + "l\n" + "\n" + "rcxhypj\n" + "jxhrcpy\n" + "cvjwhxyr\n" + "\n" + "k\n" + "k\n" + "k\n" + "k\n"
            + "tk\n" + "\n" + "nckmsaqbyu\n" + "amsqutbkcny\n" + "qvkausncybm\n" + "xkabdomuqyncs\n" + "nbmsuzkyqica\n" + "\n"
            + "fmykuezs\n" + "ymwkzspfrug\n" + "isyfuvmknlz\n" + "mfyknzivslu\n" + "\n" + "zjegqtakx\n" + "eztjkxgamq\n"
            + "kozgqxjiate\n" + "aoegxjztqk\n" + "evazknxdgjqpt\n" + "\n" + "vgsxdnkjbfhiaetcprluo\n" + "dtnuvboigfpehkslxrca\n"
            + "\n" + "cwomixyvlubhk\n" + "oaqsvyfhgxzenjdt\n" + "\n" + "zfm\n" + "mz\n" + "hixzmusvwrae\n" + "mz\n"
            + "cljzomp\n" + "\n" + "aimzewnqpdfy\n" + "hwqfnrpjymatid\n" + "pnweyqagxmifsd\n" + "\n" + "jagrtqsikbnm\n"
            + "takgijrnmbsq\n" + "tqkasinmgrjb\n" + "kgrajsmtqbni\n" + "njbtigamsqkr\n" + "\n" + "us\n" + "su\n" + "su\n" + "\n"
            + "oxdmjrcfluiwyz\n" + "zqkmrgditwhocxfj\n" + "\n" + "nmdwq\n" + "uwdqkvn\n" + "jrneyiwoxat\n" + "\n" + "o\n"
            + "o\n" + "o\n" + "\n" + "thqpmc\n" + "tzlqhbep\n" + "qpeth\n" + "wnjtdqvashgpo\n" + "\n" + "forgjwbimycezkaqsuv\n"
            + "evsarxjwikbyguqofczm\n" + "kmciyqvrgubsjazefow\n" + "\n" + "dnzjkpraybifesmgt\n" + "gbnpizsfaetdryjmk\n"
            + "tedmfpsajrznbiygk\n" + "bjypsrntedmkiagfz\n" + "ptugzdvlaeynbrimjkfs\n" + "\n" + "ahgfxmszervkt\n"
            + "khnfsrdwexgzicm\n" + "uoehlpmxyfrgszb\n" + "\n" + "a\n" + "a\n" + "qa\n" + "\n" + "bscjlkuietnfmvhqa\n"
            + "zpmdysghcukrxwql\n" + "\n" + "ybxngswmtzlv\n" + "tlrnfwbsgzxvm\n" + "\n" + "szdfxgvuiyjkola\n"
            + "yfkgxdzisjlmau\n" + "fujmxskalzgidy\n" + "\n" + "slgcrih\n" + "rqhgl\n" + "ctrylh\n" + "zaholrxk\n" + "ldqihr\n"
            + "\n" + "c\n" + "z\n" + "a\n" + "\n" + "l\n" + "ol\n" + "l\n" + "l\n" + "l\n" + "\n" + "yijuzlomvp\n"
            + "mojpuylivz\n" + "ozvmpyjliu\n" + "zvjulmpoiy\n" + "\n" + "inxdohsz\n" + "zosindxh\n" + "qxnhsizdo\n" + "\n"
            + "nwxljyekmazfbh\n" + "akwzqbylxdirjomg\n" + "\n" + "kowimsdrbjcnxtauhpzel\n" + "mucayqfvogjwelnhtr\n" + "\n"
            + "d\n" + "d\n" + "d\n" + "\n" + "spnrxclg\n" + "kcnprgsl\n" + "lngcvrsp\n" + "grnelshcp\n" + "gnizpcjsrl\n" + "\n"
            + "cshdbjovlfnkaezmwqipt\n" + "tkdpzrfiwhcbmveonlaqs\n" + "wsmpkrlhvbieaonzdqtfc\n" + "\n" + "mjlotdgyzucrxnkp\n"
            + "oyxumpbjngrldftkz\n" + "lrtzmxjsguknoypd\n" + "xmqrugyntjkpdzol\n" + "kyojtmrpgudxznl\n" + "\n"
            + "cwvpnuyjxelgkabi\n" + "ajliexnugckvpbwy\n" + "xiebpgvnkwlayucmoj\n" + "vlgewuabjkncxpyi\n" + "\n"
            + "cngbduwxzsa\n" + "vbdjnpaczu\n" + "zkjcandobyu\n" + "boacduknz\n" + "jcnuadbmzvp\n" + "\n"
            + "armxudckhoyjqbtli\n" + "kcynhliroatmuxbqd\n" + "abcroqxklidyhtm\n" + "hlcmaxobrktydeifq\n" + "lkqxichayojdrbmt\n"
            + "\n" + "slthvjp\n" + "tsvhp\n" + "sjhypgitv\n" + "petvzhs\n" + "svhipt\n" + "\n" + "xzmcwdjlnqtyboak\n"
            + "dhwyjfxlqckmtozanb\n" + "bczotlnmdkwaqxyj\n" + "wqtybjxamkzldhcon\n" + "qtnmgwdcyoakrvbzxslj\n" + "\n"
            + "gyrolihnftx\n" + "ywlhbxfoumigr\n" + "dfoihgrapeuxyl\n" + "\n" + "juredoybhpalsxkmztwvgnicqf\n"
            + "yzuceqoikxgvpaflbrdjmwhstn\n" + "\n" + "mhwkugfvsr\n" + "syicghpunw\n" + "snphygwuc\n" + "nusgwh\n" + "\n"
            + "nxystlabuqzcfwdik\n" + "ucyaztnkdm\n" + "zgcrndkatyuh\n" + "oadutnkzcy\n" + "\n" + "rftpkiwz\n" + "fwkczpt\n"
            + "\n" + "kwbpsjlvhrcumifgeaxn\n" + "fbxgslwjmnucrpkeiav\n" + "evikuwganplzrbxfjcms\n" + "mfripxsbvaeckuwlgnj\n"
            + "\n" + "xlsekqbnoj\n" + "keqjlxsoib\n" + "gojbxelqsk\n" + "\n" + "tduwp\n" + "udt\n" + "\n" + "fyivbg\n" + "age\n"
            + "lnpckwdumgoszq\n" + "\n" + "vtdm\n" + "dmtv\n" + "mtdv\n" + "mtvd\n" + "\n" + "sxqcuwzdlpter\n"
            + "uzpesxlrqdctw\n" + "dcfmszreptwxqolu\n" + "\n" + "mlbezcfirsxnughtpajvwdq\n" + "eswufgarhxmdvcybiznljt\n"
            + "umgbwcadfiovrxknhszlejt\n" + "\n" + "hoif\n" + "wrdvuxj\n" + "kgloem\n" + "bmngy\n" + "\n" + "ta\n" + "ty\n"
            + "fsgnmtbq\n" + "\n" + "wzucbvdygxeparqhslomjif\n" + "rulbgvdpsmzihjqcwfyoexa\n" + "glaicvjyhdwmupsebrozqfx\n"
            + "qloepvwjszdahxbufykmgcri\n" + "aqjexmwyuczgdhropibvlsf\n" + "\n" + "lsdikhoarexcmu\n" + "ygdjrhzmku\n"
            + "hkpjdrmub\n" + "bhukrdgm\n" + "\n" + "xyrohb\n" + "eg\n" + "p\n" + "e\n" + "\n" + "eqnbpzlhmxskrfy\n"
            + "xtguwjadpciv\n" + "\n" + "k\n" + "tb\n" + "\n" + "ipoyng\n" + "phqfxkeyg\n" + "\n" + "mqfpoj\n" + "mojfqp\n"
            + "jpmofq\n" + "jqpfmo\n" + "mojqfp\n" + "\n" + "tsjrguiplcqnwxkdhfo\n" + "lspukzenrgfhtqxdwoj\n"
            + "ofxgqlduwnptrkjhs\n" + "\n" + "a\n" + "x\n" + "u\n" + "\n" + "bfpdkihjuz\n" + "nqvgjyk\n" + "olkjy\n" + "\n"
            + "zdkwbghexisn\n" + "izwngysbdxhe\n" + "dsebogwihxnz\n" + "zhnxepwgbsdi\n" + "snzhwdxegbi\n" + "\n" + "koupnhmi\n"
            + "spkmut\n" + "pgutkm\n" + "\n" + "qcytokhmwdarzx\n" + "pktnxglqrsz\n" + "rekxjqbuzsti\n" + "\n" + "vluoh\n"
            + "abhoulv\n" + "vhuodl\n" + "uovlh\n" + "\n" + "xpqhfuimjzstyecvgla\n" + "mfcgetpuhyzvljxqska\n"
            + "itlyxguqmfahsecpvjzn\n" + "xbgrtoazjulhscypemqf\n" + "tjplsvandfzyemqcghux\n" + "\n" + "oudlrfq\n" + "qofrdulz\n"
            + "\n" + "cqaxm\n" + "mdyibnoxe\n" + "\n" + "pc\n" + "cqm\n" + "lrovgwjh\n" + "xbzt\n" + "\n" + "r\n" + "r\n"
            + "r\n" + "r\n" + "\n" + "wenypm\n" + "tvzkqaihjrldusbcof\n" + "\n" + "qsjnkitvmogydzul\n" + "bzqwxkg\n"
            + "zceakgq\n" + "cqkpfgzx\n" + "kzqrhg\n" + "\n" + "xjk\n" + "kxj\n" + "jxk\n" + "xkj\n" + "xkj\n" + "\n"
            + "rpjwnm\n" + "rpwnm\n" + "\n" + "foixgd\n" + "xdgsi\n" + "\n" + "ldiwcrqgfztuonyespmjh\n"
            + "cendtkpwuzoyfsgjharqi\n" + "qztuedonysxfcwghjbrip\n" + "cgtijqzbefnpovuhrsydw\n" + "\n" + "hnuojmr\n"
            + "lmhnuj\n" + "urvhjman\n" + "gnuxpmchjk\n" + "onumtjhy\n" + "\n" + "mksn\n" + "qjsolvyktu\n" + "\n"
            + "jixlamkwrcotzfvnyup\n" + "uwndpoetkfxzqcvgras\n" + "\n" + "mlurhwbpezjgayoki\n" + "gjwcheubrlpkyozxm\n"
            + "eysbprwjcukldohngmz\n" + "oejmghpxkybzurldw\n" + "goplbuhrymwekjz\n" + "\n" + "gdi\n" + "v\n" + "uao\n" + "h\n"
            + "j\n" + "\n" + "eotq\n" + "yrfz\n" + "\n" + "xf\n" + "zxfp\n" + "xf\n" + "\n" + "jvcknhizeyopx\n" + "abgfs\n"
            + "\n" + "xdhnia\n" + "tdhiaxn\n" + "xihnda\n" + "hdnxia\n" + "ahxdni\n" + "\n" + "cvfuohwdqmsj\n" + "usjvqohdcmw\n"
            + "qshwovcumjxd\n" + "\n" + "ewcxpunrfo\n" + "ncfxeupowr\n" + "neucwxprfo\n" + "onxewrfcup\n" + "\n" + "h\n" + "h\n"
            + "h\n" + "h\n" + "h\n" + "\n" + "etqny\n" + "tiuoqws\n" + "vbfyqtzd\n" + "kaqxmthgclp\n" + "jrqtu\n" + "\n"
            + "tkylicfwajbmqz\n" + "aqjwctliysokxfb\n" + "\n" + "pohmrbxse\n" + "rspxeimobh\n" + "\n" + "topbkx\n" + "akoxr\n"
            + "oxbk\n" + "\n" + "rfixzuqejpco\n" + "orecijpuqfx\n" + "rixqejofucp\n" + "fpurciqoexj\n" + "xpqouicejfr\n" + "\n"
            + "irvl\n" + "lv\n" + "\n" + "jlbtmhk\n" + "tjahe\n" + "\n" + "fycatxuj\n" + "efmsru\n" + "vgbzwolufn\n" + "fduyp\n"
            + "\n" + "qpovf\n" + "oupvq\n" + "pvobkq\n" + "qzoplv\n" + "\n" + "uvbzsmd\n" + "szdrobh\n" + "\n" + "sohcdqkxlb\n"
            + "kbdoq\n" + "qdbkzo\n" + "qknodb\n" + "qodbk\n" + "\n" + "wlikpav\n" + "plnwzvreak\n" + "klwjovpa\n"
            + "ialpwsfvkj\n" + "\n" + "nzswdxachlvukeyprbqtmo\n" + "aulktbvnzwoyehxmfcrqps\n" + "\n" + "cdbrvskoujqzlyxpfi\n"
            + "pkljysocqvdrbueixfm\n" + "ibsyupvkfjxoldqrc\n" + "sprcluoxbfkdjqyizv\n" + "\n" + "dulfhtqpnszabcx\n"
            + "ptibcnahdurlsfqx\n" + "dxfaqcpbhstlnru\n" + "bdxtfvmhlqasopnuc\n" + "satpglqhfbcxudn\n" + "\n"
            + "fwmnrayciqxujegtlhzsk\n" + "gyakijxmslrzwtqncuef\n" + "rilkmgtxfwjszqanyceu\n" + "hwmnsizfgqltyarjkcuxe\n"
            + "pxutjdwsclbgfrmnaeyqkzi\n" + "\n" + "cdgvmqewjhobyt\n" + "cibsqlxrk\n" + "\n" + "vzncysgojwrfqxi\n"
            + "pgivscjroxnqwfyz\n" + "zrijfowgsyvxnqc\n" + "qygjhbnwfxozlvicsr\n" + "oisgwxvnrjycfzq\n" + "\n" + "bzgdqm\n"
            + "mgdfz\n" + "gzmd\n" + "dmqkzrg\n" + "mstzlidjg\n" + "\n" + "lqfnedzwckxuamrsbhjip\n" + "pzilqrxtfswogecdav\n"
            + "\n" + "s\n" + "s\n" + "z\n" + "\n" + "wm\n" + "wm\n" + "wim\n" + "twjqm\n" + "wim\n" + "\n" + "lrxagomjwhncfy\n"
            + "hbfdjsolgymarwcx\n" + "amuhoclgvfpzwxjryi\n" + "nlfmwoahdgrjxcy\n" + "\n" + "ux\n" + "a\n" + "mwzc\n" + "\n"
            + "xhsapcqjkum\n" + "vdkquacsxijpmt\n" + "hpajmqklcxsgu\n" + "\n" + "rymaftlzunxocwhgs\n" + "uxtwrncsfzohpgyl\n"
            + "yohwnrtzfkcgsulx\n" + "\n" + "hzyflavwpnexbgr\n" + "lzvfhgrxpebwa\n" + "gzphbewafvlxr\n" + "evgxhzbrpwlfa\n"
            + "\n" + "baygtmsorczixvejfh\n" + "zgrjmytxefabishcvo\n" + "jyvxgofmarisctwehzb\n" + "\n" + "ozbwxdfakrthqc\n"
            + "kcxftawdrobqzh\n" + "zqxahfdrtcwobk\n" + "xczwfkaqdhbort\n" + "akxfztqbrohcdw\n" + "\n" + "cklb\n" + "kc\n"
            + "\n" + "iaymow\n" + "muwoyi\n" + "mihywo\n" + "yaouikwm\n" + "\n" + "drtlioynkumajzshbpxcvq\n"
            + "wdovutrflknzbmqchpsygje\n" + "\n" + "aunct\n" + "jtasuf\n" + "\n" + "otybmvxqkeianrhpsw\n"
            + "zkaphbuqxoywtvrei\n" + "hlwkrtifbqyoaevxp\n" + "rvkhasoxpebqwtyi\n" + "\n" + "mqpynkuoteafwcszhdxrg\n"
            + "tuxkcrypafgbqmnohsew\n" + "uymgxcnqeakwhfptrso\n" + "\n" + "nb\n" + "k\n" + "u\n" + "\n" + "oacmsvdy\n" + "\n"
            + "tlgeajvodcspqmnrzwixkhyubf\n" + "lqhrinwycugfopbstjkezmxd\n" + "\n" + "bajwthnox\n" + "phbtjna\n"
            + "kicnbjtfaeh\n" + "\n" + "upcd\n" + "rcuds\n" + "cupnd\n" + "dcpu\n" + "\n" + "usodtpgbxrleizwcnfvhakqy\n"
            + "fhungotvpyrxdjkqziemcbla\n" + "vlkezrqchjdbagfouityxpn\n" + "\n" + "enlctogvyz\n" + "vczpwdgsoyqljknbrmt\n"
            + "lcnvyotxgzu\n" + "flgnvtyozc\n" + "tzcyvneolg\n" + "\n" + "z\n" + "t\n" + "\n" + "kzgwrn\n" + "wzrisnk\n" + "\n"
            + "fcznyxtwa\n" + "wczxnp\n" + "\n" + "modnyjbvgzck\n" + "zncvfomkdbgyj\n" + "mbcgyozvkinjd\n" + "\n"
            + "lpyvkoawcigmszdhunrtj\n" + "oygwlmuhvjptzcrksinda\n" + "pudhgtjkwaclsivmnryzfo\n" + "\n" + "av\n" + "ajh\n"
            + "avt\n" + "\n" + "apondg\n" + "ngvef\n" + "\n" + "ipxhv\n" + "wqdivtpxl\n" + "irvx\n" + "xiemubayv\n" + "irxwv\n"
            + "\n" + "othvi\n" + "vehz\n" + "hvxldcez\n" + "\n" + "gcwksjv\n" + "euxzbwgyfkjc\n" + "ksjgwc\n" + "kjgcw\n" + "\n"
            + "vsmpidclexktgoa\n" + "xpkdcgmsetloa\n" + "\n" + "wmbphlzfisxg\n" + "tovkbqyzsfpl\n" + "\n" + "pegjkcnywbhr\n"
            + "lzkgjbenxwaqyc\n" + "\n" + "vnfgtzw\n" + "ouhvagqycpsdtlwikne\n" + "vwbzgnt\n" + "nwvmbgt\n" + "\n"
            + "uzvjphxfcqg\n" + "piqjfunmaxvkzes\n" + "ufpjzxvq\n" + "vzxfjgpuq\n" + "puhjfvzwdqx\n" + "\n" + "gcn\n" + "cgn\n"
            + "inegk\n" + "nguc\n" + "\n" + "nrtl\n" + "ldthqxi\n" + "thl\n" + "dhltp\n" + "\n" + "lqopsckhyjtw\n"
            + "kaqxicgdzywevfbu\n" + "\n" + "lpodcxkyjevg\n" + "dvklycxgwpoeq\n" + "pxelgdcoykv\n" + "covedbykglpx\n"
            + "brpcyexidgvkol\n" + "\n" + "tapwumcjxbeok\n" + "jvaxthlypumkibce\n" + "xipmyuecatk\n" + "ectpdamxzquknh\n"
            + "umxarptcgeks\n" + "\n" + "dhabkrtxyepluofsqn\n" + "yfluxizrmepchjndsvak\n" + "\n" + "j\n" + "se\n" + "\n"
            + "gahmztkwboqelpiu\n" + "tlhqpmugawkoxzif\n" + "\n" + "tsquf\n" + "qstf\n" + "\n" + "qalg\n" + "zcij\n" + "wsgvl\n"
            + "\n" + "wdbrxt\n" + "wltx\n" + "wlxt\n" + "xwlt\n" + "\n" + "ovfegbwyxdq\n" + "bwxqdmygtevuz\n" + "gqxwdyvbe\n"
            + "\n" + "ohx\n" + "oht\n" + "hrzo\n" + "hto\n" + "\n" + "cxfg\n" + "jxf\n" + "ifx\n" + "lfx\n" + "xf\n" + "\n"
            + "yguq\n" + "gqyzu\n" + "oqguts\n" + "qgu\n" + "ugq\n" + "\n" + "dchajzrwvkptfmsi\n" + "zkrhavifwtcdsjmpx\n"
            + "vtfpsckaimwrdhzj\n" + "zpmscahjfvkwtrid\n" + "dzawcriphmskvjft\n" + "\n" + "ebmwykdnfpqzlursx\n" + "lcfhzqed\n"
            + "vlzfqaed\n" + "elfizqd\n" + "ofqehzdl\n" + "\n" + "fhyzodpvjg\n" + "dgwjybzov\n" + "\n" + "pfbzsvrw\n"
            + "vbspwfz\n" + "vanuzbpwfds\n" + "sbzpvfw\n" + "wpvftzbs\n" + "\n" + "sjtvukw\n" + "wscktjuv\n" + "ustjkwv\n"
            + "jtwgukvs\n" + "uwtvnskj\n" + "\n" + "ylkne\n" + "jetb\n" + "reo\n" + "lpeor\n" + "\n" + "sutbnz\n" + "dnts\n"
            + "tsn\n" + "\n" + "riyn\n" + "riy\n" + "riy\n" + "\n" + "ygbzxlwfrp\n" + "lxpwyfgzrb\n" + "wrlzbxpgsyf\n" + "\n"
            + "slbkhm\n" + "lbmschf\n" + "\n" + "u\n" + "u\n" + "u\n" + "u\n" + "qu\n" + "\n" + "lmdnixreobwgkz\n"
            + "znigbyrdowxmekl\n" + "emolgxwrkidbnz\n" + "edbmlonrigkwzx\n" + "kdbzworeigxmln\n" + "\n" + "wbvohcntuzgkiqle\n"
            + "kjzvybxedwnpfrtc\n" + "ktjwcmyvnsbez\n" + "\n" + "bprfjknlqxszmody\n" + "nlxfmpzadjosrbqye\n"
            + "fbmsaujxdirztyopwqln\n" + "pnxqsmdhgoybzlvjcf\n" + "fomtripxnljbdqzys\n" + "\n" + "kcpygiesudlbvtfzxham\n"
            + "nrdlbxmgeaczitjuoqhw\n" + "\n" + "dg\n" + "xnkt\n" + "\n" + "bfwdtrizlpheavuyqnjos\n"
            + "ubydfogztjraphnevswilq\n" + "\n" + "w\n" + "w\n" + "ew\n" + "w\n" + "w\n" + "\n" + "a\n" + "xd\n" + "aj\n" + "\n"
            + "gbdzh\n" + "dglqr\n" + "\n" + "vudclgx\n" + "dkjhwel\n" + "lrtsydb\n" + "\n" + "gxzqm\n" + "oin\n" + "\n"
            + "yzpuwnrosctjgivd\n" + "bgwmfkslpden\n" + "pmasgdnewq\n" + "\n" + "nle\n" + "en\n" + "ne\n" + "\n" + "hbkdavilf\n"
            + "bloxksadhvi\n" + "hvjbudailk\n" + "ivhjladbky\n" + "\n" + "vdscgflymnxubrjqaptwi\n" + "tmgphwfsnikcruzbvejqyo\n"
            + "\n" + "zbplsicnrh\n" + "glczrbps\n" + "\n" + "brntwcqvh\n" + "nbqhctpwvr\n" + "\n" + "va\n" + "prbzmhv\n" + "\n"
            + "l\n" + "g\n" + "q\n" + "p\n" + "\n" + "jfu\n" + "qjovgdfmu\n" + "fju\n" + "ujf\n" + "juf\n" + "\n"
            + "nhajypktod\n" + "hjietodnscxfk\n" + "\n" + "rxvemgzo\n" + "woxmskrgyn\n" + "\n" + "bgra\n" + "egrab\n" + "rbga\n"
            + "grmvqba\n" + "gabr\n" + "\n" + "oblcizsupdm\n" + "dxuolpbzrmic\n" + "lpbucidzom\n" + "plbzmodicu\n" + "\n"
            + "suivo\n" + "v\n" + "pnvt\n" + "wv\n" + "\n" + "c\n" + "uc\n" + "c\n" + "c\n" + "c\n" + "\n" + "afu\n" + "a\n"
            + "\n" + "ow\n" + "wo\n" + "wo\n" + "ow\n" + "oewu\n" + "\n" + "m\n" + "iqm\n" + "\n" + "fatyhbmqngwcepkor\n"
            + "lpixamknzesdvjo\n" + "\n" + "tgkqb\n" + "mikub\n" + "kb\n" + "\n" + "oad\n" + "doyafpkh\n" + "mshkdco\n"
            + "sowd\n" + "qidberovngj\n" + "\n" + "kaqvlfyijdozbt\n" + "rqwsbfhoavzt\n" + "atqfszvrnob\n" + "\n"
            + "svqrgkwuilhzxcmpyjf\n" + "yihumlabkroxzcqswg\n" + "xushykmcqzgtilwr\n" + "ukwhlqsgirnxmyzc\n"
            + "kgdrwxmlzuyicsqh\n" + "\n" + "xgcvbqyzdtn\n" + "bxzvqdytgcn\n" + "\n" + "tejri\n" + "jte\n" + "etj\n" + "etj\n"
            + "jte\n" + "\n" + "ismgw\n" + "wigsm\n" + "gsdmwpi\n" + "\n" + "kdhuyt\n" + "ypkhd\n" + "kdhy\n" + "kohdy\n"
            + "hydk\n" + "\n" + "tseoqvwhuxbr\n" + "ldykeurcijnfh\n" + "\n" + "ab\n" + "ba\n" + "\n" + "ocm\n" + "omcp\n"
            + "wzjmfto\n" + "mo\n" + "\n" + "vuzyadlnrgbos\n" + "zojynudrsav\n" + "dctmqfyevrixhpuzkans\n" + "\n" + "kwm\n"
            + "k\n" + "k\n" + "k\n" + "k\n" + "\n" + "sexvtzkumgnrl\n" + "wxdfeiocglqnhmsb\n" + "mnvaelgxksr\n" + "\n"
            + "numlhsatpefgdxrwjc\n" + "tpgfejhnrdmlawcxs\n" + "xdwracgsthmlfjpne\n" + "\n" + "jfnlsprcqha\n" + "alzqjcnsrhpf\n"
            + "hlfjrqcpna\n" + "qacrflhjnp\n" + "tcimfrdnhlqwxyjape\n" + "\n" + "bihwtnofygkmlrasjp\n" + "nkmzwhagborfsjipu\n"
            + "\n" + "mbh\n" + "hmbo\n" + "qwjkvhziclput\n" + "mrhb\n" + "yxhe\n" + "\n" + "blqgwcin\n" + "amxzqdwpbrhonyci\n"
            + "neqcbiw\n" + "wcnfiukqvb\n" + "ciekwbtnqg\n" + "\n" + "ezsxhnrctpayukgfl\n" + "uhfcxpyltzngksre\n"
            + "xfqcpntyzuglreshk\n" + "yxugczlrstkpeafhn\n" + "nplzeygrhtskfxcu\n" + "\n" + "bhu\n" + "hm\n" + "h\n" + "xh\n"
            + "\n" + "o\n" + "o\n" + "o\n" + "o\n" + "o\n" + "\n" + "zfeyitdlxj\n" + "jeiqgo\n" + "gjevqui\n" + "eoikrsj\n"
            + "\n" + "eci\n" + "ice\n" + "orwbites\n" + "\n" + "linomaq\n" + "mnqagilo\n" + "qimlnoa\n" + "nlgmquio\n"
            + "lirmnqvho\n" + "\n" + "gvqiyfphlxbwcotrszame\n" + "iberhzpovmxwytqlcfsga\n" + "wzsyatgrmilpfbhocqxve\n" + "\n"
            + "qykaloifucdmsxh\n" + "dilsfxmyurjqab\n" + "\n" + "fljib\n" + "wuseoqk\n" + "\n" + "kryuaec\n" + "hkuap\n"
            + "ivkzwltojugf\n" + "\n" + "emrywzsgpkqtjuav\n" + "kphozgjyrqsmavwt\n" + "vjketymzpawqsgru\n" + "zwrhvjyqakgmspt\n"
            + "qkztgyrjavdfspwm\n" + "\n" + "cufk\n" + "juck\n" + "wcqkd\n" + "kcosr\n" + "\n" + "wymkfrvugb\n" + "brgkwvymu\n"
            + "brukgswmy\n" + "pmykbwugr\n" + "rugnkmbyw\n" + "\n" + "cfzsnlvougeb\n" + "krhatewdigj\n" + "\n" + "a\n" + "jw\n"
            + "w\n" + "vkml\n" + "w\n" + "\n" + "mbzltykicoxgnqjs\n" + "jkbyiqcnmzgoaxstef\n" + "bpghumytxjizcskqno\n" + "\n"
            + "ckq\n" + "qkc\n" + "ckq\n" + "\n" + "crygfszhdx\n" + "xrzopcyhsd\n" + "\n" + "eshnuqkyid\n" + "fvhdutyzec\n"
            + "\n" + "y\n" + "y\n" + "y\n" + "co\n" + "\n" + "opifqrgwclbka\n" + "ugqoibrawck\n" + "caqufogmbipkrw\n"
            + "gswcojayirqhbk\n" + "\n" + "kptv\n" + "kprsal\n" + "vslga\n" + "wi\n" + "zfcqhej\n" + "\n"
            + "mgxrjbkqpycvodwzsiet\n" + "zwqkdbjsmtpeygvc\n" + "qewtzbghpydcmvksj\n" + "\n" + "bnteshjdfwpl\n" + "plcrqhdxn\n"
            + "\n" + "xezumahpsktiwjylq\n" + "sjytilphzaqeuxm\n" + "eulximpazqsyjht\n" + "\n" + "wofatncugil\n" + "prd\n"
            + "p\n" + "shx\n" + "exsj\n" + "\n" + "rbsyhmqilpuz\n" + "hkjaotxcfe\n" + "\n" + "rvpdqnkbyshltegifxja\n"
            + "vseaxdyqiktjhrbfnlg\n" + "lxbtgqjaesyifvkndrhp\n" + "laqyivwjmsbnxfdrktzgech\n" + "\n" + "khmoucji\n"
            + "umkiohc\n" + "\n" + "axnjc\n" + "acsjnx\n" + "nxawcj\n" + "cxanj\n" + "nawjxc\n" + "\n" + "qhjtuv\n" + "uqvjt\n"
            + "jqtvu\n" + "\n" + "odbruemawlviy\n" + "vwgery\n" + "\n" + "qnlwkidepuh\n" + "ldqnkuefhw\n" + "lthxdewqjkugaons\n"
            + "\n" + "lctym\n" + "ycqthox\n" + "\n" + "moej\n" + "ojeuz\n" + "joe\n" + "djyeo\n" + "eoj\n" + "\n"
            + "fwdeqrzicj\n" + "dcrewjzifqg\n" + "qmcjfiezpwrvd\n" + "ncwzqrdijfe\n" + "\n" + "kaczplh\n" + "khxaplyc\n"
            + "uhbdnckolaqgjp\n" + "vhlrswcapk\n" + "\n" + "envxjbidtrkq\n" + "bdkyrxntvizqme\n" + "psrkdftwxqbnevli\n" + "\n"
            + "b\n" + "b\n" + "jg\n" + "\n" + "j\n" + "byt\n" + "hfsw\n" + "t\n" + "iy\n" + "\n" + "uexapjs\n" + "caxdepujs\n"
            + "suapejx\n" + "pjsaexu\n" + "useajxp\n" + "\n" + "qiuotlgvewkfbx\n" + "eiovbxuwdtkflgq\n" + "uwkiqvbrgpflte\n"
            + "gfbvweihkqtlu\n" + "kulgiwfqebtv\n" + "\n" + "ekd\n" + "dke\n" + "vkde\n" + "kemdg\n" + "dek\n" + "\n"
            + "kmhfyos\n" + "fkyhsmo\n" + "yosfmkh\n" + "\n" + "arubwxqszlvmhndtfygpi\n" + "dpfvlgsytzqxnhmwabuir\n"
            + "gvaiutxnbydzwqprfslmh\n" + "wtgszuandpiyrbfvhmlqx\n" + "\n" + "prkfqibx\n" + "fkrqxbpi\n" + "rpixfbqka\n" + "\n"
            + "cmthfprlzxvg\n" + "chzgaxjkpwrl\n" + "dhybeprslocun\n" + "\n" + "pdrc\n" + "rpcd\n" + "dcpr\n" + "\n" + "nsi\n"
            + "vlsig\n" + "ins\n" + "si";
    public static void main(String[] args) {
        countQuestions(INPUT);
    }
    private static void countQuestions(String input2) {
        var groups = input2.split("\n{2,}");
        var count  = 0;
        for (String group : groups) {
            count += Integer.bitCount(unifyQuestions(group));
        }
        System.out.println("counted " + count + " ");
    }
    private static int unifyQuestions(String group) {
        var people    = group.split("\n");
        var questions = -1;
        for (var person : people) {
            questions &= parsePersonalAnswers(person);
        }
        System.out.println("group " + group.replace('\n', '/') + " answered " + Integer.toBinaryString(questions));
        return questions;
    }
    private static int parsePersonalAnswers(String person) {
        var questions = 0;
        for (var i = 0; i < person.length(); ++i) {
            var c = person.charAt(i);
            if (c < 'a' || c > 'z') {
                continue;
            }
            questions |= 1 << (c - 'a');
        }
        System.out.println(person + " answered " + Integer.toBinaryString(questions));
        return questions;
    }

}
